name: meetmind
description: "The most powerful meeting AI tool"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Networking
  web_socket_channel: ^3.0.2

  # Audio
  record: ^6.2.0
  permission_handler: ^11.4.0

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2

  # Utils
  uuid: ^4.5.1
  intl: ^0.19.0
  ffi: ^2.1.4
  path_provider: ^2.1.5
  crypto: ^3.0.6
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
